//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.jonthysell.Chordious.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.jonthysell.Chordious.WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string BackgroundNoneFriendlyValue {
            get {
                return ResourceManager.GetString("BackgroundNoneFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string BackgroundTransparentFriendlyValue {
            get {
                return ResourceManager.GetString("BackgroundTransparentFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string BackgroundWhiteFriendlyValue {
            get {
                return ResourceManager.GetString("BackgroundWhiteFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious failed to start because a copy of Chordious is already running..
        /// </summary>
        internal static string ChordiousAlreadyRunningErrorMessage {
            get {
                return ResourceManager.GetString("ChordiousAlreadyRunningErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious.
        /// </summary>
        internal static string ChordiousDialogCaption {
            get {
                return ResourceManager.GetString("ChordiousDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious crashed exception: {0}.
        /// </summary>
        internal static string ChordiousUnhandledExceptionMessageFormat {
            get {
                return ResourceManager.GetString("ChordiousUnhandledExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious {0} is available. Would you like to update now?.
        /// </summary>
        internal static string ChordiousUpdateAvailableUpdateNowMessageFormat {
            get {
                return ResourceManager.GetString("ChordiousUpdateAvailableUpdateNowMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious is up-to-date..
        /// </summary>
        internal static string ChordiousUpdateNotAvailableMessage {
            get {
                return ResourceManager.GetString("ChordiousUpdateNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Background.
        /// </summary>
        internal static string DiagramEditorSelectedEditorRendererBackgroundLabel {
            get {
                return ResourceManager.GetString("DiagramEditorSelectedEditorRendererBackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background to show behind the diagrams..
        /// </summary>
        internal static string DiagramEditorSelectedEditorRendererBackgroundToolTip {
            get {
                return ResourceManager.GetString("DiagramEditorSelectedEditorRendererBackgroundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DiagramExportChooseOutputPathLabel {
            get {
                return ResourceManager.GetString("DiagramExportChooseOutputPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for the path to export to..
        /// </summary>
        internal static string DiagramExportChooseOutputPathToolTip {
            get {
                return ResourceManager.GetString("DiagramExportChooseOutputPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        internal static string DiagramExportExampleFilenameFormatLabel {
            get {
                return ResourceManager.GetString("DiagramExportExampleFilenameFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An example of what the image filename will be..
        /// </summary>
        internal static string DiagramExportExampleFilenameFormatToolTip {
            get {
                return ResourceManager.GetString("DiagramExportExampleFilenameFormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string DiagramExportOutputPathLabel {
            get {
                return ResourceManager.GetString("DiagramExportOutputPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where you want to export the diagram image files..
        /// </summary>
        internal static string DiagramExportOutputPathToolTip {
            get {
                return ResourceManager.GetString("DiagramExportOutputPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Files.
        /// </summary>
        internal static string DiagramExportOverwriteFilesLabel {
            get {
                return ResourceManager.GetString("DiagramExportOverwriteFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite files that already exist with the same name..
        /// </summary>
        internal static string DiagramExportOverwriteFilesToolTip {
            get {
                return ResourceManager.GetString("DiagramExportOverwriteFilesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string DiagramExportScaleFactorLabel {
            get {
                return ResourceManager.GetString("DiagramExportScaleFactorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale the image files to what percentage of the original size..
        /// </summary>
        internal static string DiagramExportScaleFactorToolTip {
            get {
                return ResourceManager.GetString("DiagramExportScaleFactorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string DiagramExportSelectedExportFormatLabel {
            get {
                return ResourceManager.GetString("DiagramExportSelectedExportFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the exported image files..
        /// </summary>
        internal static string DiagramExportSelectedExportFormatToolTip {
            get {
                return ResourceManager.GetString("DiagramExportSelectedExportFormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string DiagramExportSelectedFilenameFormatLabel {
            get {
                return ResourceManager.GetString("DiagramExportSelectedFilenameFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to format the filenames of the exported images. Codes as follows:
        ///%c - Diagram collection name
        ///%t - Diagram title text
        ///%h - Diagram height (in pixels)
        ///%w - Diagram width (in pixels)
        ///%x - Image extension (lowercase)
        ///%X - Image extension (uppercase)
        ///%0 - Diagram number (starts at 0)
        ///%1 - Diagram number (starts at 1)
        ///%# - Total number of diagrams to be exported
        ///%% - Percent sign.
        /// </summary>
        internal static string DiagramExportSelectedFilenameFormatToolTip {
            get {
                return ResourceManager.GetString("DiagramExportSelectedFilenameFormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for installing Chordious! Would you like Chordious to check for updates when it starts? (Recommended) You can change your mind later in Options..
        /// </summary>
        internal static string FirstRunMessage {
            get {
                return ResourceManager.GetString("FirstRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        internal static string OptionsCheckForUpdatesAsyncLabel {
            get {
                return ResourceManager.GetString("OptionsCheckForUpdatesAsyncLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually check online for updates..
        /// </summary>
        internal static string OptionsCheckForUpdatesAsyncToolTip {
            get {
                return ResourceManager.GetString("OptionsCheckForUpdatesAsyncToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates On Start.
        /// </summary>
        internal static string OptionsCheckUpdateOnStartLabel {
            get {
                return ResourceManager.GetString("OptionsCheckUpdateOnStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious will check for updates automatically when the app starts..
        /// </summary>
        internal static string OptionsCheckUpdateOnStartToolTip {
            get {
                return ResourceManager.GetString("OptionsCheckUpdateOnStartToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Checked.
        /// </summary>
        internal static string OptionsLastUpdateCheckLabel {
            get {
                return ResourceManager.GetString("OptionsLastUpdateCheckLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string OptionsLastUpdateCheckNeverCheckedValue {
            get {
                return ResourceManager.GetString("OptionsLastUpdateCheckNeverCheckedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last time that Chordious checked for updates..
        /// </summary>
        internal static string OptionsLastUpdateCheckToolTip {
            get {
                return ResourceManager.GetString("OptionsLastUpdateCheckToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Editor.
        /// </summary>
        internal static string OptionsSelectedEditorRendererBackgroundLabel {
            get {
                return ResourceManager.GetString("OptionsSelectedEditorRendererBackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background to show behind the diagrams in the Diagram Editor..
        /// </summary>
        internal static string OptionsSelectedEditorRendererBackgroundToolTip {
            get {
                return ResourceManager.GetString("OptionsSelectedEditorRendererBackgroundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Channel.
        /// </summary>
        internal static string OptionsSelectedReleaseChannelLabel {
            get {
                return ResourceManager.GetString("OptionsSelectedReleaseChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release channel that you want to get updates from..
        /// </summary>
        internal static string OptionsSelectedReleaseChannelToolTip {
            get {
                return ResourceManager.GetString("OptionsSelectedReleaseChannelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string OptionsSelectedRendererBackgroundLabel {
            get {
                return ResourceManager.GetString("OptionsSelectedRendererBackgroundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background to show behind the diagrams in the Chordious UI..
        /// </summary>
        internal static string OptionsSelectedRendererBackgroundToolTip {
            get {
                return ResourceManager.GetString("OptionsSelectedRendererBackgroundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string OptionsSettingsBackgroundGroupLabel {
            get {
                return ResourceManager.GetString("OptionsSettingsBackgroundGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string OptionsUpdatesGroupLabel {
            get {
                return ResourceManager.GetString("OptionsUpdatesGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official.
        /// </summary>
        internal static string ReleaseChannelOfficialFriendlyValue {
            get {
                return ResourceManager.GetString("ReleaseChannelOfficialFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string ReleaseChannelPreviewFriendlyValue {
            get {
                return ResourceManager.GetString("ReleaseChannelPreviewFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious failed to load the user config.
        ///
        ///Backup: {0}
        ///
        ///Send this file and the details below to the developer and they may be able to fix it..
        /// </summary>
        internal static string ResetAndBackupUserConfigBackupFileMessageFormat {
            get {
                return ResourceManager.GetString("ResetAndBackupUserConfigBackupFileMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious failed to read your user config file. The file may be corrupt or damaged. Would you like to load Chordious anyway?
        ///
        ///&quot;No&quot; will exit Chordious immediately.
        ///
        ///&quot;Yes&quot; will make a backup of your current config then reset all of Chordious to a clean install. (You&apos;ll lose all of your diagrams, custom instruments, etc., but you may be able to recover them later from the backup.).
        /// </summary>
        internal static string ResetAndBackupUserConfigConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetAndBackupUserConfigConfirmationMessage", resourceCulture);
            }
        }
    }
}
