//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.jonthysell.Chordious.WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.jonthysell.Chordious.WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious failed to start because a copy of Chordious is already running..
        /// </summary>
        internal static string ChordiousAlreadyRunningErrorMessage {
            get {
                return ResourceManager.GetString("ChordiousAlreadyRunningErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious.
        /// </summary>
        internal static string ChordiousDialogCaption {
            get {
                return ResourceManager.GetString("ChordiousDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious crashed exception: {0}.
        /// </summary>
        internal static string ChordiousUnhandledExceptionMessageFormat {
            get {
                return ResourceManager.GetString("ChordiousUnhandledExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious {0} is available. Would you like to update now?.
        /// </summary>
        internal static string ChordiousUpdateAvailableUpdateNowMessageFormat {
            get {
                return ResourceManager.GetString("ChordiousUpdateAvailableUpdateNowMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious is up-to-date..
        /// </summary>
        internal static string ChordiousUpdateNotAvailableMessage {
            get {
                return ResourceManager.GetString("ChordiousUpdateNotAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official.
        /// </summary>
        internal static string ReleaseChannelOfficialFriendlyValue {
            get {
                return ResourceManager.GetString("ReleaseChannelOfficialFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string ReleaseChannelPreviewFriendlyValue {
            get {
                return ResourceManager.GetString("ReleaseChannelPreviewFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious failed to load the user config.
        ///
        ///Backup: {0}
        ///
        ///Send this file and the details below to the developer and they may be able to fix it..
        /// </summary>
        internal static string ResetAndBackupUserConfigBackupFileMessageFormat {
            get {
                return ResourceManager.GetString("ResetAndBackupUserConfigBackupFileMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chordious failed to read your user config file. The file may be corrupt or damaged. Would you like to load Chordious anyway?
        ///
        ///&quot;No&quot; will exit Chordious immediately.
        ///
        ///&quot;Yes&quot; will make a backup of your current config then reset all of Chordious to a clean install. (You&apos;ll lose all of your diagrams, custom instruments, etc., but you may be able to recover them later from the backup.).
        /// </summary>
        internal static string ResetAndBackupUserConfigConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetAndBackupUserConfigConfirmationMessage", resourceCulture);
            }
        }
    }
}
