//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.jonthysell.Chordious.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.jonthysell.Chordious.Core.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        internal static string AppConfigFileFriendlyLevel {
            get {
                return ResourceManager.GetString("AppConfigFileFriendlyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fretboard diagram generator for stringed instruments..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre Arc Ratio.
        /// </summary>
        internal static string BarreArcRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("BarreArcRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre Color.
        /// </summary>
        internal static string BarreLineColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("BarreLineColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre Thickness.
        /// </summary>
        internal static string BarreLineThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("BarreLineThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre Opacity.
        /// </summary>
        internal static string BarreOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("BarreOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A barre cannot span from string {0} to string {1}..
        /// </summary>
        internal static string BarrePositionInvalidSpanExceptionMessage {
            get {
                return ResourceManager.GetString("BarrePositionInvalidSpanExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre Stack.
        /// </summary>
        internal static string BarreStackFriendlyKeyName {
            get {
                return ResourceManager.GetString("BarreStackFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string BarreTypeOptionFullFriendlyValue {
            get {
                return ResourceManager.GetString("BarreTypeOptionFullFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string BarreTypeOptionNoneFriendlyValue {
            get {
                return ResourceManager.GetString("BarreTypeOptionNoneFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial.
        /// </summary>
        internal static string BarreTypeOptionPartialFriendlyValue {
            get {
                return ResourceManager.GetString("BarreTypeOptionPartialFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre Alignment.
        /// </summary>
        internal static string BarreVerticalAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("BarreVerticalAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barre Visible.
        /// </summary>
        internal static string BarreVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("BarreVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BooleanFalseFriendlyValue {
            get {
                return ResourceManager.GetString("BooleanFalseFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BooleanTrueFriendlyValue {
            get {
                return ResourceManager.GetString("BooleanTrueFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Border Color.
        /// </summary>
        internal static string BottomMarkBorderColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkBorderColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Border Thickness.
        /// </summary>
        internal static string BottomMarkBorderThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkBorderThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Color.
        /// </summary>
        internal static string BottomMarkColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Font Family.
        /// </summary>
        internal static string BottomMarkFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Opacity.
        /// </summary>
        internal static string BottomMarkOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Radius Ratio.
        /// </summary>
        internal static string BottomMarkRadiusRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkRadiusRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Shape.
        /// </summary>
        internal static string BottomMarkShapeFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkShapeFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Text Alignment.
        /// </summary>
        internal static string BottomMarkTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Text Color.
        /// </summary>
        internal static string BottomMarkTextColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkTextColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Text Opacity.
        /// </summary>
        internal static string BottomMarkTextOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkTextOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Text Size Ratio.
        /// </summary>
        internal static string BottomMarkTextSizeRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkTextSizeRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Text Style.
        /// </summary>
        internal static string BottomMarkTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Text Visible.
        /// </summary>
        internal static string BottomMarkTextVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkTextVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Mark Visible.
        /// </summary>
        internal static string BottomMarkVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("BottomMarkVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resize the diagram due to existing marks, fret labels, and/or barres..
        /// </summary>
        internal static string CantResizeDiagramExceptionMessage {
            get {
                return ResourceManager.GetString("CantResizeDiagramExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ChordiousKeyNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ChordiousKeyNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Settings.
        /// </summary>
        internal static string ChordiousSettingsFriendlyLevelFormat {
            get {
                return ResourceManager.GetString("ChordiousSettingsFriendlyLevelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chord quality &quot;{0}&quot; already exists..
        /// </summary>
        internal static string ChordQualityAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("ChordQualityAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chord quality &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ChordQualityNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ChordQualityNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultConfigFileFriendlyLevel {
            get {
                return ResourceManager.GetString("DefaultConfigFileFriendlyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Marks.
        /// </summary>
        internal static string DiagramBarreStackOverMarksFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramBarreStackOverMarksFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Marks.
        /// </summary>
        internal static string DiagramBarreStackUnderMarksFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramBarreStackUnderMarksFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Border Color.
        /// </summary>
        internal static string DiagramBorderColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("DiagramBorderColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Border Thickness.
        /// </summary>
        internal static string DiagramBorderThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("DiagramBorderThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string DiagramCollectionFriendlyLevel {
            get {
                return ResourceManager.GetString("DiagramCollectionFriendlyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A diagram collection named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string DiagramCollectionNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("DiagramCollectionNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagram collection &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string DiagramCollectionNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DiagramCollectionNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Color.
        /// </summary>
        internal static string DiagramColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("DiagramColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string DiagramFriendlyLevel {
            get {
                return ResourceManager.GetString("DiagramFriendlyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string DiagramHorizontalAlignmentCenterFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramHorizontalAlignmentCenterFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string DiagramHorizontalAlignmentLeftFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramHorizontalAlignmentLeftFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string DiagramHorizontalAlignmentRightFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramHorizontalAlignmentRightFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Horizontal &amp; Vertical Padding.
        /// </summary>
        internal static string DiagramLabelLayoutModelAddPaddingBothFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramLabelLayoutModelAddPaddingBothFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Horizontal Padding.
        /// </summary>
        internal static string DiagramLabelLayoutModelAddPaddingHorizontalFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramLabelLayoutModelAddPaddingHorizontalFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vertical Padding.
        /// </summary>
        internal static string DiagramLabelLayoutModelAddPaddingVerticalFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramLabelLayoutModelAddPaddingVerticalFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Label Layout Model.
        /// </summary>
        internal static string DiagramLabelLayoutModelFriendlyKeyName {
            get {
                return ResourceManager.GetString("DiagramLabelLayoutModelFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string DiagramLabelLayoutModelOverlapFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramLabelLayoutModelOverlapFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord Name.
        /// </summary>
        internal static string DiagramLabelStyleChordNameFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramLabelStyleChordNameFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string DiagramLabelStyleRegularFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramLabelStyleRegularFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Collection.
        /// </summary>
        internal static string DiagramLibraryDefaultNewCollectionName {
            get {
                return ResourceManager.GetString("DiagramLibraryDefaultNewCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string DiagramLibraryFriendlyLevel {
            get {
                return ResourceManager.GetString("DiagramLibraryFriendlyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string DiagramMarkShapeCircleFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkShapeCircleFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        internal static string DiagramMarkShapeDiamondFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkShapeDiamondFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DiagramMarkShapeNoneFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkShapeNoneFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string DiagramMarkShapeSquareFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkShapeSquareFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string DiagramMarkShapeXFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkShapeXFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string DiagramMarkTypeBottomFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkTypeBottomFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        internal static string DiagramMarkTypeMutedFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkTypeMutedFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string DiagramMarkTypeNormalFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkTypeNormalFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string DiagramMarkTypeOpenFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkTypeOpenFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root.
        /// </summary>
        internal static string DiagramMarkTypeOpenRootFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkTypeOpenRootFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string DiagramMarkTypeRootFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramMarkTypeRootFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Opacity.
        /// </summary>
        internal static string DiagramOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("DiagramOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Orientation.
        /// </summary>
        internal static string DiagramOrientationFriendlyKeyName {
            get {
                return ResourceManager.GetString("DiagramOrientationFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string DiagramOrientationLeftRightFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramOrientationLeftRightFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string DiagramOrientationUpDownFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramOrientationUpDownFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Style.
        /// </summary>
        internal static string DiagramStyleFriendlyLevelFormat {
            get {
                return ResourceManager.GetString("DiagramStyleFriendlyLevelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string DiagramTextStyleBoldFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramTextStyleBoldFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold &amp; Italic.
        /// </summary>
        internal static string DiagramTextStyleBoldItalicFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramTextStyleBoldItalicFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string DiagramTextStyleItalicFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramTextStyleItalicFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string DiagramTextStyleRegularFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramTextStyleRegularFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string DiagramVerticalAlignmentBottomFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramVerticalAlignmentBottomFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string DiagramVerticalAlignmentMiddleFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramVerticalAlignmentMiddleFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string DiagramVerticalAlignmentTopFriendlyValue {
            get {
                return ResourceManager.GetString("DiagramVerticalAlignmentTopFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element already exists at this position..
        /// </summary>
        internal static string ElementAlreadyExistsAtPositionExceptionMessage {
            get {
                return ResourceManager.GetString("ElementAlreadyExistsAtPositionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element position is off of the fretboard..
        /// </summary>
        internal static string ElementPositionOffFretboardExceptionMessage {
            get {
                return ResourceManager.GetString("ElementPositionOffFretboardExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Font Family.
        /// </summary>
        internal static string FretLabelFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Grid Padding.
        /// </summary>
        internal static string FretLabelGridPaddingFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelGridPaddingFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string FretLabelSideLeftFriendlyValue {
            get {
                return ResourceManager.GetString("FretLabelSideLeftFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string FretLabelSideRightFriendlyValue {
            get {
                return ResourceManager.GetString("FretLabelSideRightFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Text Alignment.
        /// </summary>
        internal static string FretLabelTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Text Color.
        /// </summary>
        internal static string FretLabelTextColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelTextColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Text Opacity.
        /// </summary>
        internal static string FretLabelTextOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelTextOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Text Size Ratio.
        /// </summary>
        internal static string FretLabelTextSizeRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelTextSizeRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Text Style.
        /// </summary>
        internal static string FretLabelTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Text Visible.
        /// </summary>
        internal static string FretLabelTextVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelTextVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret Label Text Width Ratio.
        /// </summary>
        internal static string FretLabelTextWidthRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("FretLabelTextWidthRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Color.
        /// </summary>
        internal static string GridColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Fret Spacing.
        /// </summary>
        internal static string GridFretSpacingFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridFretSpacingFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Line Color.
        /// </summary>
        internal static string GridLineColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridLineColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Line Thickness.
        /// </summary>
        internal static string GridLineThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridLineThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Margin Bottom.
        /// </summary>
        internal static string GridMarginBottomFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridMarginBottomFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Margin.
        /// </summary>
        internal static string GridMarginFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridMarginFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Margin Left.
        /// </summary>
        internal static string GridMarginLeftFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridMarginLeftFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Margin Right.
        /// </summary>
        internal static string GridMarginRightFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridMarginRightFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Margin Top.
        /// </summary>
        internal static string GridMarginTopFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridMarginTopFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Nut Ratio.
        /// </summary>
        internal static string GridNutRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridNutRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Nut Visible.
        /// </summary>
        internal static string GridNutVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridNutVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Opacity.
        /// </summary>
        internal static string GridOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid String Spacing.
        /// </summary>
        internal static string GridStringSpacingFriendlyKeyName {
            get {
                return ResourceManager.GetString("GridStringSpacingFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instrument named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string InstrumentNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("InstrumentNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instrument &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string InstrumentNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("InstrumentNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuning &quot;{1}&quot; does not belong to the instrument &quot;{0}&quot;..
        /// </summary>
        internal static string InstrumentTuningMismatchExceptionMessage {
            get {
                return ResourceManager.GetString("InstrumentTuningMismatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified is not a valid color..
        /// </summary>
        internal static string InvalidColorArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidColorArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified is not a valid note..
        /// </summary>
        internal static string InvalidNoteArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidNoteArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The level &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string LevelNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("LevelNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Border Color.
        /// </summary>
        internal static string MarkBorderColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkBorderColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Border Thickness.
        /// </summary>
        internal static string MarkBorderThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkBorderThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Color.
        /// </summary>
        internal static string MarkColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Font Family.
        /// </summary>
        internal static string MarkFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Opacity.
        /// </summary>
        internal static string MarkOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Radius Ratio.
        /// </summary>
        internal static string MarkRadiusRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkRadiusRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Shape.
        /// </summary>
        internal static string MarkShapeFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkShapeFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Text Alignment.
        /// </summary>
        internal static string MarkTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Text Color.
        /// </summary>
        internal static string MarkTextColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkTextColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Text Opacity.
        /// </summary>
        internal static string MarkTextOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkTextOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MarkTextOptionNoneFriendlyValue {
            get {
                return ResourceManager.GetString("MarkTextOptionNoneFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Flats.
        /// </summary>
        internal static string MarkTextOptionShowNotePreferFlatsFriendlyValue {
            get {
                return ResourceManager.GetString("MarkTextOptionShowNotePreferFlatsFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Sharps.
        /// </summary>
        internal static string MarkTextOptionShowNotePreferSharpsFriendlyValue {
            get {
                return ResourceManager.GetString("MarkTextOptionShowNotePreferSharpsFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Both.
        /// </summary>
        internal static string MarkTextOptionShowNoteShowBothFriendlyValue {
            get {
                return ResourceManager.GetString("MarkTextOptionShowNoteShowBothFriendlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Text Size Ratio.
        /// </summary>
        internal static string MarkTextSizeRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkTextSizeRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Text Style.
        /// </summary>
        internal static string MarkTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Text Visible.
        /// </summary>
        internal static string MarkTextVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkTextVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Visible.
        /// </summary>
        internal static string MarkVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("MarkVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Border Color.
        /// </summary>
        internal static string MutedMarkBorderColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkBorderColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Border Thickness.
        /// </summary>
        internal static string MutedMarkBorderThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkBorderThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Color.
        /// </summary>
        internal static string MutedMarkColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Font Family.
        /// </summary>
        internal static string MutedMarkFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Opacity.
        /// </summary>
        internal static string MutedMarkOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Radius Ratio.
        /// </summary>
        internal static string MutedMarkRadiusRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkRadiusRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Shape.
        /// </summary>
        internal static string MutedMarkShapeFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkShapeFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Text Alignment.
        /// </summary>
        internal static string MutedMarkTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Text Color.
        /// </summary>
        internal static string MutedMarkTextColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkTextColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Text Opacity.
        /// </summary>
        internal static string MutedMarkTextOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkTextOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Text Size Ratio.
        /// </summary>
        internal static string MutedMarkTextSizeRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkTextSizeRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Text Style.
        /// </summary>
        internal static string MutedMarkTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Text Visible.
        /// </summary>
        internal static string MutedMarkTextVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkTextVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted Mark Visible.
        /// </summary>
        internal static string MutedMarkVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("MutedMarkVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The named interval &quot;{0}&quot; already exists..
        /// </summary>
        internal static string NamedIntervalAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("NamedIntervalAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The named interval &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string NamedIntervalNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NamedIntervalNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Diagram Num Frets.
        /// </summary>
        internal static string NewDiagramNumFretsFriendlyKeyName {
            get {
                return ResourceManager.GetString("NewDiagramNumFretsFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Diagram Num Strings.
        /// </summary>
        internal static string NewDiagramNumStringsFriendlyKeyName {
            get {
                return ResourceManager.GetString("NewDiagramNumStringsFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} could not be modified because it is marked read-only..
        /// </summary>
        internal static string ObjectIsReadOnlyExceptionMessage {
            get {
                return ResourceManager.GetString("ObjectIsReadOnlyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Border Color.
        /// </summary>
        internal static string OpenMarkBorderColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkBorderColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Border Thickness.
        /// </summary>
        internal static string OpenMarkBorderThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkBorderThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Color.
        /// </summary>
        internal static string OpenMarkColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Font Family.
        /// </summary>
        internal static string OpenMarkFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Opacity.
        /// </summary>
        internal static string OpenMarkOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Radius Ratio.
        /// </summary>
        internal static string OpenMarkRadiusRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkRadiusRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Shape.
        /// </summary>
        internal static string OpenMarkShapeFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkShapeFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Text Alignment.
        /// </summary>
        internal static string OpenMarkTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Text Color.
        /// </summary>
        internal static string OpenMarkTextColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkTextColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Text Opacity.
        /// </summary>
        internal static string OpenMarkTextOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkTextOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Text Size Ratio.
        /// </summary>
        internal static string OpenMarkTextSizeRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkTextSizeRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Text Style.
        /// </summary>
        internal static string OpenMarkTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Text Visible.
        /// </summary>
        internal static string OpenMarkTextVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkTextVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Mark Visible.
        /// </summary>
        internal static string OpenMarkVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenMarkVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Border Color.
        /// </summary>
        internal static string OpenRootMarkBorderColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkBorderColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Border Thickness.
        /// </summary>
        internal static string OpenRootMarkBorderThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkBorderThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Color.
        /// </summary>
        internal static string OpenRootMarkColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Font Family.
        /// </summary>
        internal static string OpenRootMarkFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Opacity.
        /// </summary>
        internal static string OpenRootMarkOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Radius Ratio.
        /// </summary>
        internal static string OpenRootMarkRadiusRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkRadiusRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Shape.
        /// </summary>
        internal static string OpenRootMarkShapeFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkShapeFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Text Alignment.
        /// </summary>
        internal static string OpenRootMarkTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Text Color.
        /// </summary>
        internal static string OpenRootMarkTextColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkTextColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Text Opacity.
        /// </summary>
        internal static string OpenRootMarkTextOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkTextOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Text Size Ratio.
        /// </summary>
        internal static string OpenRootMarkTextSizeRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkTextSizeRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Text Style.
        /// </summary>
        internal static string OpenRootMarkTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Text Visible.
        /// </summary>
        internal static string OpenRootMarkTextVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkTextVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Root Mark Visible.
        /// </summary>
        internal static string OpenRootMarkVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("OpenRootMarkVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object does not have a parent..
        /// </summary>
        internal static string ParentNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ParentNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library path &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string PathNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("PathNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Border Color.
        /// </summary>
        internal static string RootMarkBorderColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkBorderColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Border Thickness.
        /// </summary>
        internal static string RootMarkBorderThicknessFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkBorderThicknessFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Color.
        /// </summary>
        internal static string RootMarkColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Font Family.
        /// </summary>
        internal static string RootMarkFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Opacity.
        /// </summary>
        internal static string RootMarkOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Radius Ratio.
        /// </summary>
        internal static string RootMarkRadiusRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkRadiusRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Shape.
        /// </summary>
        internal static string RootMarkShapeFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkShapeFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Text Alignment.
        /// </summary>
        internal static string RootMarkTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Text Color.
        /// </summary>
        internal static string RootMarkTextColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkTextColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Text Opacity.
        /// </summary>
        internal static string RootMarkTextOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkTextOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Text Size Ratio.
        /// </summary>
        internal static string RootMarkTextSizeRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkTextSizeRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Text Style.
        /// </summary>
        internal static string RootMarkTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Text Visible.
        /// </summary>
        internal static string RootMarkTextVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkTextVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Mark Visible.
        /// </summary>
        internal static string RootMarkVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("RootMarkVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale &quot;{0}&quot; already exists..
        /// </summary>
        internal static string ScaleAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("ScaleAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ScaleNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ScaleNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Color.
        /// </summary>
        internal static string TitleColorFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleColorFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Font Family.
        /// </summary>
        internal static string TitleFontFamilyFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleFontFamilyFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Grid Padding.
        /// </summary>
        internal static string TitleGridPaddingFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleGridPaddingFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Label Style.
        /// </summary>
        internal static string TitleLabelStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleLabelStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Opacity.
        /// </summary>
        internal static string TitleOpacityFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleOpacityFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Text Alignment.
        /// </summary>
        internal static string TitleTextAlignmentFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleTextAlignmentFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Text Size.
        /// </summary>
        internal static string TitleTextSizeFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleTextSizeFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Text Size Mod Ratio.
        /// </summary>
        internal static string TitleTextSizeModRatioFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleTextSizeModRatioFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Text Style.
        /// </summary>
        internal static string TitleTextStyleFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleTextStyleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Visible.
        /// </summary>
        internal static string TitleVisibleFriendlyKeyName {
            get {
                return ResourceManager.GetString("TitleVisibleFriendlyKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuning &quot;{0}&quot; already exists..
        /// </summary>
        internal static string TuningAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("TuningAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuning &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string TuningNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("TuningNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserConfigFileFriendlyLevel {
            get {
                return ResourceManager.GetString("UserConfigFileFriendlyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with {0}..
        /// </summary>
        internal static string WatermarkFormat {
            get {
                return ResourceManager.GetString("WatermarkFormat", resourceCulture);
            }
        }
    }
}
