//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.jonthysell.Chordious.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.jonthysell.Chordious.Core.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A barre cannot span from string {0} to string {1}..
        /// </summary>
        internal static string BarrePositionInvalidSpanExceptionMessage {
            get {
                return ResourceManager.GetString("BarrePositionInvalidSpanExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resize the diagram due to existing marks, fret labels, and/or barres..
        /// </summary>
        internal static string CantResizeDiagramExceptionMessage {
            get {
                return ResourceManager.GetString("CantResizeDiagramExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ChordiousKeyNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ChordiousKeyNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chord quality named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string ChordQualityNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("ChordQualityNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chord quality &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ChordQualityNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ChordQualityNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A diagram collection named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string DiagramCollectionNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("DiagramCollectionNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagram collection &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string DiagramCollectionNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DiagramCollectionNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element already exists at this position..
        /// </summary>
        internal static string ElementAlreadyExistsAtPositionExceptionMessage {
            get {
                return ResourceManager.GetString("ElementAlreadyExistsAtPositionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element position is off of the fretboard..
        /// </summary>
        internal static string ElementPositionOffFretboardExceptionMessage {
            get {
                return ResourceManager.GetString("ElementPositionOffFretboardExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An instrument named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string InstrumentNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("InstrumentNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instrument &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string InstrumentNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("InstrumentNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuning &quot;{1}&quot; does not belong to the instrument &quot;{0}&quot;..
        /// </summary>
        internal static string InstrumentTuningMismatchExceptionMessage {
            get {
                return ResourceManager.GetString("InstrumentTuningMismatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified is not a valid color..
        /// </summary>
        internal static string InvalidColorArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidColorArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified is not a valid note..
        /// </summary>
        internal static string InvalidNoteArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidNoteArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The level &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string LevelNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("LevelNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} could not be modified because it is marked read-only..
        /// </summary>
        internal static string ObjectIsReadOnlyExceptionMessage {
            get {
                return ResourceManager.GetString("ObjectIsReadOnlyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object does not have a parent..
        /// </summary>
        internal static string ParentNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ParentNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library path &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string PathNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("PathNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scale named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string ScaleNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("ScaleNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string ScaleNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ScaleNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tuning named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string TuningNameAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("TuningNameAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tuning &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string TuningNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("TuningNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with {0}..
        /// </summary>
        internal static string WatermarkFormat {
            get {
                return ResourceManager.GetString("WatermarkFormat", resourceCulture);
            }
        }
    }
}
