//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.jonthysell.Chordious.Core.ViewModel.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.jonthysell.Chordious.Core.ViewModel.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data could not be validated: {0}.
        /// </summary>
        internal static string AdvancedDataValidationErrorMessage {
            get {
                return ResourceManager.GetString("AdvancedDataValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone....
        /// </summary>
        internal static string CloneLabel {
            get {
                return ResourceManager.GetString("CloneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        internal static string CountLabel {
            get {
                return ResourceManager.GetString("CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone &quot;{0}&quot;....
        /// </summary>
        internal static string DiagramLibraryCloneNodeLabelFormat {
            get {
                return ResourceManager.GetString("DiagramLibraryCloneNodeLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a clone of collection &quot;{0}&quot; named:.
        /// </summary>
        internal static string DiagramLibraryCloneNodePromptFormat {
            get {
                return ResourceManager.GetString("DiagramLibraryCloneNodePromptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy of the selected collection..
        /// </summary>
        internal static string DiagramLibraryCloneNodeToolTip {
            get {
                return ResourceManager.GetString("DiagramLibraryCloneNodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new collection named:.
        /// </summary>
        internal static string DiagramLibraryCreateNodePrompt {
            get {
                return ResourceManager.GetString("DiagramLibraryCreateNodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new collection..
        /// </summary>
        internal static string DiagramLibraryCreateNodeToolTip {
            get {
                return ResourceManager.GetString("DiagramLibraryCreateNodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &quot;{0}&quot;.
        /// </summary>
        internal static string DiagramLibraryDeleteNodeLabelFormat {
            get {
                return ResourceManager.GetString("DiagramLibraryDeleteNodeLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the collection &quot;{0}&quot;. This cannot be undone. Do you want to continue?.
        /// </summary>
        internal static string DiagramLibraryDeleteNodePromptFormat {
            get {
                return ResourceManager.GetString("DiagramLibraryDeleteNodePromptFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected collection..
        /// </summary>
        internal static string DiagramLibraryDeleteNodeToolTip {
            get {
                return ResourceManager.GetString("DiagramLibraryDeleteNodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the {0} selected diagrams. This cannot be undone. Do you want to continue?.
        /// </summary>
        internal static string DiagramLibraryDeleteSelectedDiagramsPromptPluralFormat {
            get {
                return ResourceManager.GetString("DiagramLibraryDeleteSelectedDiagramsPromptPluralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete the selected diagram. This cannot be undone. Do you want to continue?.
        /// </summary>
        internal static string DiagramLibraryDeleteSelectedDiagramsPromptSingleFormat {
            get {
                return ResourceManager.GetString("DiagramLibraryDeleteSelectedDiagramsPromptSingleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;{0}&quot;....
        /// </summary>
        internal static string DiagramLibraryEditNodeLabelFormat {
            get {
                return ResourceManager.GetString("DiagramLibraryEditNodeLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected collection&apos;s properties..
        /// </summary>
        internal static string DiagramLibraryEditNodeToolTip {
            get {
                return ResourceManager.GetString("DiagramLibraryEditNodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        internal static string DiagramLibraryNodesLabel {
            get {
                return ResourceManager.GetString("DiagramLibraryNodesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your collections of diagrams..
        /// </summary>
        internal static string DiagramLibraryNodesToolTip {
            get {
                return ResourceManager.GetString("DiagramLibraryNodesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one diagram can be edited at a time. Please select a single diagram and try again..
        /// </summary>
        internal static string DiagramLibraryOnlyOneDiagramCanBeEditedMessage {
            get {
                return ResourceManager.GetString("DiagramLibraryOnlyOneDiagramCanBeEditedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram Library.
        /// </summary>
        internal static string DiagramLibraryTitle {
            get {
                return ResourceManager.GetString("DiagramLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception details: {0}.
        /// </summary>
        internal static string ExceptionViewModelDetailsFormat {
            get {
                return ResourceManager.GetString("ExceptionViewModelDetailsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        internal static string ExportLabel {
            get {
                return ResourceManager.GetString("ExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string LaunchWebsiteLabel {
            get {
                return ResourceManager.GetString("LaunchWebsiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Chordious website..
        /// </summary>
        internal static string LaunchWebsiteToolTip {
            get {
                return ResourceManager.GetString("LaunchWebsiteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        internal static string NewLabel {
            get {
                return ResourceManager.GetString("NewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone the {0} selected diagrams..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeCloneSelectedToolTipPluralFormat {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeCloneSelectedToolTipPluralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone the selected diagram..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeCloneSelectedToolTipSingleFormat {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeCloneSelectedToolTipSingleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new diagram..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeCreateDiagramToolTip {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeCreateDiagramToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the {0} selected diagrams..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeDeleteSelectedToolTipPluralFormat {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeDeleteSelectedToolTipPluralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected diagram..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeDeleteSelectedToolTipSingleFormat {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeDeleteSelectedToolTipSingleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the selected diagram..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeEditSelectedToolTip {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeEditSelectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the {0} selected diagrams as image files..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeExportSelectedToolTipPluralFormat {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeExportSelectedToolTipPluralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the selected diagram as an image file..
        /// </summary>
        internal static string ObservableDiagramLibraryNodeExportSelectedToolTipSingleFormat {
            get {
                return ResourceManager.GetString("ObservableDiagramLibraryNodeExportSelectedToolTipSingleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string PathLabel {
            get {
                return ResourceManager.GetString("PathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:.
        /// </summary>
        internal static string SelectedLabel {
            get {
                return ResourceManager.GetString("SelectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord Finder.
        /// </summary>
        internal static string ShowChordFinderLabel {
            get {
                return ResourceManager.GetString("ShowChordFinderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for chords with the Chord Finder..
        /// </summary>
        internal static string ShowChordFinderToolTip {
            get {
                return ResourceManager.GetString("ShowChordFinderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string ShowDiagramLibraryLabel {
            get {
                return ResourceManager.GetString("ShowDiagramLibraryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage collections of your favorite diagrams..
        /// </summary>
        internal static string ShowDiagramLibraryToolTip {
            get {
                return ResourceManager.GetString("ShowDiagramLibraryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ShowHelpLabel {
            get {
                return ResourceManager.GetString("ShowHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Help section on the Chordious website..
        /// </summary>
        internal static string ShowHelpToolTip {
            get {
                return ResourceManager.GetString("ShowHelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        internal static string ShowInstrumentManagerLabel {
            get {
                return ResourceManager.GetString("ShowInstrumentManagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and manage your favorite instruments and tunings..
        /// </summary>
        internal static string ShowInstrumentManagerToolTip {
            get {
                return ResourceManager.GetString("ShowInstrumentManagerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string ShowLicenseLabel {
            get {
                return ResourceManager.GetString("ShowLicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the license for using Chordious..
        /// </summary>
        internal static string ShowLicenseToolTip {
            get {
                return ResourceManager.GetString("ShowLicenseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string ShowOptionsLabel {
            get {
                return ResourceManager.GetString("ShowOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Chordious&apos; configuration..
        /// </summary>
        internal static string ShowOptionsToolTip {
            get {
                return ResourceManager.GetString("ShowOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Finder.
        /// </summary>
        internal static string ShowScaleFinderLabel {
            get {
                return ResourceManager.GetString("ShowScaleFinderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for scales with the Scale Finder..
        /// </summary>
        internal static string ShowScaleFinderToolTip {
            get {
                return ResourceManager.GetString("ShowScaleFinderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (stop asking me).
        /// </summary>
        internal static string YesAndRememberLabel {
            get {
                return ResourceManager.GetString("YesAndRememberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
